# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('owner', models.CharField(max_length=20)),
                ('case_typ', models.CharField(max_length=1000)),
                ('date_added', models.DateField(default=datetime.datetime(2017, 5, 12, 21, 54, 15, 41000))),
            ],
        ),
    ]
