# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 5, 12, 22, 17, 54, 593000)),
        ),
    ]
