# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_remove_cases_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='case_typ',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
