# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 20:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_cases_case_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='data_added',
            field=models.DateField(default=datetime.datetime(2017, 5, 11, 20, 2, 46, 553805)),
        ),
    ]
