# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 20:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_cases_data_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='data_added',
        ),
        migrations.AddField(
            model_name='cases',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 5, 11, 20, 3, 41, 536719)),
        ),
    ]
