# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 20:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20170511_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 5, 11, 20, 13, 35, 73171)),
        ),
    ]
